### ISSUE TITLE
cgi-zoom-picker

### ISSUE THREAD

**Issue by Kyrllan** [cgisoftware/cids#10]
- adicionar loading ao digitar um valor no campo do zoom até que apareca a descrição que foi definida no campo ( :ao-digitar)
- trazer a descrição mesmo que o valor seja atribuido programaticamente ao v-model do campo
![image](https://user-images.githubusercontent.com/31549101/129203041-8815faff-af6a-4540-a9fd-66e0684f0c00.png)

**Comment by booscaaa** [comment]
Verificado que o problema não estava na bilbioteca, e sim no loading da tela que removia o componente e não atualizava os valore
