### ISSUE TITLE
Colunas duplicadas

### ISSUE THREAD

**Issue by wiliamfrisonribeiro** [cgisoftware/cids#2]
- Problema com coluanas duplicadas quando salva na tela padrão em todas as tabelas.
- Base de dados usada pacific amelia-mvb, branch feature/tms-motorista, tela wtms002 e programa pacific wger008 .
- Após salvar os dados da tabela na tela padrão e fazer o reload na pagina apresenta colunas duplicadas na hora de retirar e adicionar colunas na tabela na propriendade mostra-propriedades.

**Comment by booscaaa** [comment]
Me manda a branch que tu ta trabalhando, qual programa. Lembra sempre de detalhar pra eu conseguir simular o problema
