### ISSUE TITLE
cgi-zoom-picker

### ISSUE THREAD

**Issue by Kyrllan** [cgisoftware/cids#9]
Tentar desenvolver uma maneira de chamar o zoom programaticamente sem necessidade da interação do usuario (eventos de clique)

**Comment by booscaaa** [comment]
Verifica se colocando a tag ref="" e chamando o metodo
`this.$refs.nomeDoComponenteDeZoom.chamaZoom() `

Acredito que ja complementa a alteração.

**Comment by booscaaa** [comment]
Isso funcionou?
